config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticated_constraint = lambda do |request|
    Authenticatable::SessionUser.new(request.session).signed_into_okta?
  end

  constraints authenticated_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/housing_units_list', to: 'housing_units_list#index'
  get '/unauthorized', to: 'login#unauthorized', as: :unauthorized_login
  get '/monitors/lb', to: 'monitors#service_online'

  post '/', to: "application#consume_okta"

  post '/child_form_approval/:uid', to: 'external_forms#approve', as: :approve_external_form
  delete '/child_form_approval/:uid', to: 'external_forms#disapprove', as: :disapprove_external_form

  namespace :precheck do
    get ':token', to: 'status#show', as: :status
    post ':token/confirmation', to: 'confirmation#create', as: :confirmation
    post ':token/rejection', to: 'rejection#create', as: :rejection
  end

  # Check-in routes using RESTful conventions
  get '/arrival-scan', to: 'checkins#new', as: :new_checkin
  post '/arrival-scan', to: 'checkins#new', as: :checkins
end

app/controllers/precheck/confirmation_controller.rb
class Precheck::ConfirmationController < PrecheckController
  def create
    redirect_to precheck_status_path and return unless Precheck::EligibilityService.new(family: @family).call

    hotel = params['hotel'] == 'Other' ? " OTHER - #{params['other_hotel']} " : params['hotel']
    HotelStay.create(hotel: hotel, family_id: @family.id)
 
    @family.update!(precheck_status: :approved)
    Precheck::UpdatedFamilyStatusService.new(family: @family).call
  end
end

app/controllers/precheck/rejection_controller.rb
class Precheck::RejectionController < PrecheckController
  def create
    redirect_to precheck_status_path and return if Precheck::EligibilityService.new(family: @family).too_late_or_checked_in?

    @family.update!(precheck_status: :changes_requested)
    @message = params['message']
    Precheck::UpdatedFamilyStatusService.new(family: @family, message: @message).call
  end
end

app/controllers/precheck/status_controller.rb
class Precheck::StatusController < PrecheckController
  def show
    @finances = FamilyFinances::Report.call(family: @family)
    @policy = build_policy    
    @hotels = HousingFacility.order(:position)
  end

  private

  def build_policy
    Pundit.policy(User.new(role: 'finance'), @family)
  end
end

app/controllers/precheck_controller.rb
class PrecheckController < ApplicationController
  layout 'precheck'

  skip_before_action :verify_authenticity_token, :authenticate_user!

  before_action :load_token, :load_family

  rescue_from(ActiveRecord::RecordNotFound) do |_exception|
    render 'error'
  end

  private

  def load_token
    @token = PrecheckEmailToken.find_by!(token: params['token'])
  end

  def load_family
    @family = @token.family
  end
end

app/helpers/precheck_helper.rb
module PrecheckHelper
  def precheck_eligible?(family)
    Precheck::EligibilityService.new(family: family).call
  end

  def precheck_eligibility_errors(family)
    Precheck::EligibilityService.new(family: family).errors
  end

  def precheck_eligibility_actionable_errors(family)
    Precheck::EligibilityService.new(family: family).actionable_errors
  end

  def precheck_eligibility_error_label(error, family)
    t("precheck_helper.eligibility_error_label.#{error}", names_of_children: names_of_children_without_approved_forms(family))
  end

  def names_of_children_without_approved_forms(family)
    Precheck::EligibilityService.new(family: family).children_without_approved_forms.map(&:full_name).to_sentence
  end

  def precheck_status_label(arg)
    status = arg.is_a?(Family) ? arg.precheck_status : arg
    t("precheck_helper.status_label.#{status}")
  end

  def precheck_statuses_select_collection
    Family.precheck_statuses.map do |name, _id|
      [precheck_status_label(name), name]
    end
  end

  def too_late_for_precheck?(family)
    Precheck::EligibilityService.new(family: family).too_late?
  end
end

app/views/precheck/status/_approved.html.erb
<p><%= t('family_mailer.summary.precheck_confirmed', conference: UserVariable[:conference_id]) %></p>
<br>

<p><%= t('family_mailer.summary.contact_list_preamble') %></p>
<br>

<%= t('family_mailer.summary.contact_list_html') %>
<br>
<br>

<p><%= t('family_mailer.summary.summary_preamble') %></p>
<br>
<br>

<%= render 'families/family_summary', family: family, finances: finances, policy: policy %>

app/views/precheck/status/_checked_in.html.erb
<p>
  <% if family.approved? 
    if family.anyone_registered_for_legacy_conferences? %>
      <%= t('precheck.confirmation.show.precheck_confirmed_legacy_html', conference: UserVariable[:conference_id]) %>
    <% else %>
      <%= t('precheck.confirmation.show.precheck_confirmed_html', conference: UserVariable[:conference_id]) %>
    <% end
  else %>
    <%= t('family_mailer.summary.onsite_confirmed', conference: UserVariable[:conference_id]) %>
  <% end %>
</p>
<br>

<p><%= t('family_mailer.summary.contact_list_preamble') %></p>
<br>

<%= t('family_mailer.summary.contact_list_html') %>
<br>
<br>

<p><%= t('family_mailer.summary.summary_preamble') %></p>
<br>
<br>

<%= render 'families/family_summary', family: family, finances: finances, policy: policy, without_unit: true %>

app/views/precheck/status/_not_precheck_eligible.html.erb
<% if too_late_for_precheck?(family) %>
  <%= render 'precheck/status/not_precheck_eligible/too_late_for_precheck', family: family %>
<% else %>
  <%= render 'precheck/status/not_precheck_eligible/eligibility_errors_with_form', family: family, token: token %>
<% end %>

app/views/precheck/status/_precheck_eligible.html.erb
<p><%= t('.financial_summary_preamble_html') %></p>
<br>
<br>

<%= render 'families/family_summary', family: family, finances: finances, policy: policy, without_unit: true %>

<span id='confirm'>

  <%= link_to t('.confirm_precheck'), '#', class: 'btn btn-confirm', onclick: "$('#confirm').hide(); $('#accept').show(); return false" %>

  <%= link_to t('.request_changes'), '#', class: 'btn btn-cancel', onclick: "$('#confirm').hide(); $('#reject').show(); return false" %>

</span>

<%= form_tag precheck_rejection_path(token: token), id: 'reject', style: 'display:none' do %>
  <p><%= t('.request_changes_preamble') %></p>
  <%= text_area_tag(:message, '', rows: 10, placeholder: t('.request_changes_placeholder')) %>
  <br>
  <%= submit_tag(t('.submit_request_changes'), class: 'btn btn-confirm', data: { confirm: t('.request_changes_confirm'), disable_with: '...' }) %>
  <%= link_to t('.cancel'), '#', class: 'btn btn-cancel', onclick: "$('#reject').hide(); $('#confirm').show(); return false" %>
<% end %>

<%= form_tag precheck_confirmation_path(token: token), id: 'accept', style: 'display:none' do %>
  <p><%= t('.request_hotel_confirmation_html') %></p>
  <%= select_tag(:hotel, options_for_select(["Please Select.."] + @hotels + ["Other"], 2), :onchange=> "
    if ($('#hotel').val() === 'Other') {
      $('#other_hotel').show()
      $('#confirm_precheck_confirm').hide()
    } else {
      $('#other_hotel').hide()
      $('#confirm_precheck_confirm').show()
    }
  ") %>
  <%= text_area_tag(:other_hotel, '', rows: 2, style: 'display:none', placeholder: t('.request_hotel_confirmation_other'), :onkeyup=>"$(this).val().length > 0 ? $('#confirm_precheck_confirm').show() : $('#confirm_precheck_confirm').hide()") %>
  <br>
  <%= submit_tag(t('.submit_hotel_confirmation'), id: 'confirm_precheck_confirm', style: 'display:none', class: 'btn btn-confirm', data: { confirm: t('.confirm_precheck_confirm'), disable_with: '...' }) %>
  <%= link_to t('.cancel'), '#', class: 'btn btn-cancel', onclick: "$('#accept').hide(); $('#confirm').show(); return false" %>
<% end %>

app/views/precheck/status/show.html.erb
<h2 class="greeting"><%= t('.greeting', last_name: @family.last_name) %></h2>
<br>

<% if @family.approved? || @family.checked_in? %>
  <%= render 'checked_in', family: @family, token: @token, finances: @finances, policy: @policy %>
<% elsif precheck_eligible?(@family) %>
  <%= render 'precheck_eligible', family: @family, token: @token, finances: @finances, policy: @policy, hotels: @hotels %>
<% else %>
  <%= render 'not_precheck_eligible', family: @family, token: @token, finances: @finances, policy: @policy %>
<% end %>